# Enable HTTP
quarkus.http.insecure-requests=enabled
# Setup PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ping
quarkus.transaction-manager.default-transaction-timeout=3000s
quarkus.hibernate-orm.log.queries-slower-than-ms=200
quarkus.hibernate-orm.database.generation=update
# Set port
quarkus.http.port=8080
quarkus.devservices.enabled=true
%test.quarkus.devservices.enabled=false
quarkus.datasource.password=postgres
# JWT signing / verification
mp.jwt.verify.publickey.location=publicKey
smallrye.jwt.sign.key.location=privateKey
quarkus.native.resources.includes=publicKey
# Filesystem
filesystem.default.path=${FILESYSTEM_DEFAULT_PATH:/tmp/ping}
